---
id: Service_Facebook
name: Service_Facebook
full: Facebook client library
description: Client libraries for the Facebook REST API.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Service_Facebook
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 2.0.11
  api: 2.0.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Support: ^2
      pear.horde.org/Horde_Util: ^2
    ext:
      json: '*'
      SimpleXML: '*'
